apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    secrets.doppler.com/reload: "true"
  creationTimestamp: null
  labels:
    app: magnificent-app
  name: magnificent-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: magnificent-app
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: magnificent-app
      spec:
        containers:
        - envFrom:
          - secretRef:
              name: magnificent-app-secrets
          image: nginx
          name: magnificent-app
          ports:
          - containerPort: 8000
          resources: {}
status: {}