apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    secrets.doppler.com/reload: "true"
  creationTimestamp: null
  labels:
    app: magnificent-app
  name: magnificent-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: magnificent-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: magnificent-app
    spec:
      containers:
        image: 970160214347.dkr.ecr.us-east-1.amazonaws.com/magnificent-ecr-repo:magnificent-api-master-f6ba925bcf2cb74c8d79efcfcec1910edbee2c1f
        name: magnificent-app
        ports:
        - containerPort: 8000
        resources: {}
status: {}