apiVersion: apps/v1
kind: Deployment
metadata:
  name: magnificent-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: magnificent-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: magnificent-api
    spec:
      containers:
      - name: magnificent-api
        image: django
        ports:
        - containerPort: 8000
        resources: {}
status: {}
