apiVersion: v1
kind: Service
metadata:
  name: "magnificent-app-service"
spec:
  selector:
    app: "magnificent-app"
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  type: LoadBalancer